---
- name: Deploy java program
  hosts: all
  remote_user: root

  become: yes
  tasks:
    - name: Installation docker
      shell: amazon-linux-extras install docker && systemctl start docker 
      
    - name: Create an app directory sur la machine distante
      file:
        path: /app
        state: directory
        owner: ec2-user
        mode: 0777

    - name: Copier le world.class dans la machine distante
      copy:
        src: helloWorld.class
        dest: /app
        mode: 0644

    - name: Copier le dockerfile sur machine distante
      copy:
        src: Dockerfile
        dest: /app
        mode: 0400
        
    - name: On génère l'image docker, on l'appelle formation/java:1.0
      shell: cd /app && docker build -t formation/java:1.0 .
      register: result
      
    - name: On exécute le conteneur de l'image docker formation/java:1.0
      shell: docker run --rm --name conteneur_app formation/java:1.0 
      register: result

    - debug: var=result
